version: '3.8'

services:
  mariadb-test:
    build:
      context: .
      dockerfile: Dockerfile.mariadb-test
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      TZ: UTC
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "testuser", "-ptestpass"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  mariadb-data:
