version: '3.8'

services:
  mariadb-test:
    build:
      context: .
      dockerfile: Dockerfile.mariadb-test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=testroot
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
